DROP TABLE IF EXISTS "SportRadarInfo" ;

CREATE TABLE public."SportRadarInfo" (
    id integer NOT NULL,
    play_id character varying(200) UNIQUE,
    jersey_number character varying(200),
    team_at_moment character varying(200),
    primary_position character varying(200),
    away_team_name character varying(200),
    home_team_name character varying(200),
    player_id character varying(200),
    player_game_scores character varying(200),
    player_season_average_scores character varying(200),
    total_years_experience character varying(200),
    team_at_moment_nba_id character varying(200),
    height character varying(200),
    weight character varying(200),
    current_team character varying(200),
    current_team_id character varying(200),
    home_team_nba_id character varying(200),
    away_team_nba_id character varying(200),
    draft_year character varying(200),
    draft_selection character varying(200),
    draft_round character varying(200),
    birthplace character varying(200),
    birthdate character varying(200),
    home_team_scores_first_quarter character varying(200),
    home_team_scores_second_quarter character varying(200),
    home_team_scores_third_quarter character varying(200),
    home_team_scores_quarter_quarter character varying(200),
    away_team_scores_first_quarter character varying(200),
    away_team_scores_second_quarter character varying(200),
    away_team_scores_third_quarter character varying(200),
    away_team_scores_fourth_quarter character varying(200),
    draft_team character varying(200),
    draft_team_nba_id character varying(200)
);


ALTER TABLE public."SportRadarInfo" OWNER TO "nba-content-pipeline-staging";
--
-- Name: SportRadarInfo_id_seq; Type: SEQUENCE; Schema: public; Owner: nba-content-pipeline-staging
--

ALTER TABLE public."SportRadarInfo" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."SportRadarInfo_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);